spring.application.name=Utulek

# ==========================================
# PostgreSQL – Docker (přepíše se env proměnnými z docker-compose)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/utulek_db
spring.datasource.username=utulek
spring.datasource.password=utulek_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
